name: Build Ionic Android App

on:
  push:
    branches:
      - github_action  # Change to your actual branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Ensure you use Node.js 20 or later

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Sync with Android
        run: npx cap sync android

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Android APK/AAB
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK/AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/bundle/release/*.aab

      # Option 1: Upload using 'r0adkll/google-drive-upload-action' (if available)
      - name: Upload APK/AAB to Google Drive
        uses: r0adkll/google-drive-upload-action@master
        with:
          credentials_json: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          file: android/app/build/outputs/bundle/release/*.aab
          folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        continue-on-error: true  # If this step fails, move to Option 2

      # Option 2: Upload via cURL (if previous step fails)
      - name: Upload APK/AAB via cURL
        if: failure()
        run: |
          curl -X POST -L \
          -H "Authorization: Bearer ${{ secrets.GOOGLE_ACCESS_TOKEN }}" \
          -F "metadata={name : 'release.aab', parents: ['${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}']};type=application/json;charset=UTF-8" \
          -F "file=@android/app/build/outputs/bundle/release/*.aab;type=application/octet-stream" \
          "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
