name: Build Ionic Android App

on:
  push:
    branches:
      - github_action  # Change to your actual branch

jobs:
  build:
    runs-on: ubuntu-latest  # Change to Ubuntu for better compatibility
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use Node.js 20

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Sync with Android
        run: npx cap sync android  # Sync necessary files

      - name: Build Android APK/AAB
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK/AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/bundle/release/*.aab

      - name: Install gdrive
        run: |
          curl -L -o gdrive.tar.gz https://github.com/glotlabs/gdrive/releases/latest/download/gdrive-linux-x64.tar.gz
          tar -xzf gdrive.tar.gz
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/

      - name: Authenticate gdrive
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" > gdrive_service_key.json
          gdrive about

      - name: Upload Build to Google Drive
        run: |
          gdrive upload --service-account gdrive_service_key.json --parent ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }} android/app/build/outputs/bundle/release/*.aab
