name: Build Ionic Android App

on:
  push:
    branches:
      - github_action  # Change to your actual branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu instead of macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a stable LTS version

      - name: Install Dependencies
        run: npm install --no-optional

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Build Android APK/AAB
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon
          ./gradlew bundleRelease --no-daemon

      - name: Upload APK/AAB as Artifact
        uses: actions/upload-artifact@v3.2.1  # Use a stable version
        with:
          name: android-build
          path: android/app/build/outputs/bundle/release/*.aab
