name: Build and Deploy Android Project for Capacitor

on:
  push:
    branches:
      - github_action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install dependencies
        run: |
          npm install
          npm install --save @capacitor/android

      - name: Build the Android app (Capacitor)
        run: |
          npx cap sync android
          npx cap open android
          ./gradlew assembleDebug

      - name: Install rclone
        run: |
          sudo apt-get install rclone
          mkdir -p ~/.config/rclone

      - name: Configure rclone with Google Service Account
        run: |
          echo "$GOOGLE_DRIVE_CREDENTIALS" > /tmp/sa.json
          echo '[gdrive]
          type = drive
          scope = drive
          service_account_file = /tmp/sa.json' > ~/.config/rclone/rclone.conf

      - name: Extract subdomain from APIClient.kt
        run: |
          # Extract subdomain from APIClient.kt using grep and sed
          SUBDOMAIN=$(grep "BASE_URL" android/app/src/main/java/com/bitla/mba/tsoperator/api/APIClient.kt | sed -n 's/.https:\/\/\([^.]\).*/\1/p')
          echo "SUBDOMAIN=$SUBDOMAIN" >> $GITHUB_ENV

      - name: Upload to Google Drive
        run: |
          folder_id="1Dm9WcPG8OBlQ2FDvzHFsBHm-uUV1TKN3"
          timestamp=$(date +%Y_%m_%d)
          # Use the extracted subdomain to rename APK
          mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/${SUBDOMAIN}-${timestamp}.apk
          rclone copy --verbose android/app/build/outputs/apk/debug/${SUBDOMAIN}-${timestamp}.apk gdrive:/ --drive-root-folder-id $folder_id

      - name: Upload debug APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SUBDOMAIN }}-debug
          path: android/app/build/outputs/apk/debug/*.apk
