name: Build and Upload Ionic App

on:
  push:
    branches:
      - github_action  # Change this to your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic and Capacitor
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Copy Web Files to Android
        run: npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease
          cd ..

      - name: Upload APK to Google Drive
        uses: wdzeng/google-drive-upload-action@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: android/app/build/outputs/apk/release/app-release.apk
          folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
