name: Build Ionic Android App

on:
  push:
    branches:
      - action_main  # Change to your actual branch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Ensure you use Node.js 20 or later

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Sync with Android
        run: npx cap sync android  # Sync to make sure all necessary files are present

      - name: Build Android APK/AAB
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease
      - name: Upload APK/AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/bundle/release/*.aab

  upload:
    name: Upload APK to Google Drive
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-build
          path: app

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload APK to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: |
          echo "$GDRIVE_CREDENTIALS" > credentials.json
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

          python <<EOF
          import os
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload
          from google.oauth2 import service_account

          SCOPES = ['https://www.googleapis.com/auth/drive.file']
          creds = service_account.Credentials.from_service_account_file('credentials.json', scopes=SCOPES)
          drive_service = build('drive', 'v3', credentials=creds)

          folder_id = os.getenv('GOOGLE_DRIVE_FOLDER_ID')
          file_metadata = {'name': 'app-debug.apk', 'parents': [folder_id]}
          media = MediaFileUpload('android/app/build/outputs/apk/debug/app-debug.apk', mimetype='application/vnd.android.package-archive')

          file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()
          print(f'File uploaded: {file.get("id")}')
          EOF
