name: Build and Upload Ionic App to Google Drive

on:
  push:
    branches:
      - github_action  # Change this to your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic and Capacitor
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/

      - name: Build Ionic App
        run: ionic build --prod

      - name: Copy Web Files to Android
        run: npx cap sync android

      - name: Build Android APK with Debugging
        run: |
          cd android
          ./gradlew assembleRelease --stacktrace --info
          cd ..

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.GDRIVE_RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload APK to Google Drive
        run: |
          rclone copy android/app/build/outputs/apk/release/app-release.apk gdrive:/IonicBuilds
