name: Build and Upload APK

on:
  push:
    branches:
      - action_main  # Change to your branch name if needed

jobs:
  build:
    name: Build Ionic Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Capacitor CLI
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic Project
        run: ionic build --prod

      - name: Sync Capacitor Android
        run: npx cap sync android

      - name: Build Android Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  upload:
    name: Upload APK to Google Drive
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: debug-apk
          path: .

      - name: Upload to Google Drive
        uses: andreppires/google-drive-upload-action@v1
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: "app-debug.apk"
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
