name: Build Ionic Android App

on:
  push:
    branches:
      - github_action  # Change to your actual branch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Ensure you use Node.js 20 or later

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Sync with Android
        run: npx cap sync android  # Sync to make sure all necessary files are present

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Cache Gradle wrapper
      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-${{ runner.os }}-

      - name: Build Android APK/AAB
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK/AAB to Google Drive
        uses: r0adkll/google-drive-upload-action@v1.1.0
        with:
          credentials_json: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}  # Use the uploaded secret
          file: android/app/build/outputs/bundle/release/*.aab  # Path to the .aab file
          folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }} # Optional: specify a folder ID if needed

      - name: Upload APK/AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/bundle/release/*.aab
