name: Build Ionic Android App

on:
  push:
    branches:
      - github_action  # Change to github_action if that's the intended branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change to LTS Node.js version, 16.x or 18.x

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Sync with Android
        run: npx cap sync android

      - name: Build Android APK/AAB
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK/AAB as Artifact
        uses: actions/upload-artifact@v2  # Use version 2 to avoid version issue
        with:
          name: android-build
          path: android/app/build/outputs/bundle/release/*.aab  # Correct path for the .aab file
